// <auto-generated />
using Grajciar.InternetBanking.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Grajciar.InternetBanking.Infrastructure.Migrations
{
    [DbContext(typeof(InternetBankingDbContext))]
    partial class InternetBankingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Grajciar.InternetBanking.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Petr",
                            LastName = "Grajciar",
                            Username = "petrgrajciar"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Karel",
                            LastName = "Chleba",
                            Username = "karel"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Šimon",
                            LastName = "Rohlík",
                            Username = "simon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
